# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42765d10d342c17730fff3d35deb034875a2d964fd93e4c7d1419b977be5a4334c19b1e3051ff72fc1f928350485484aae2f62668d7f7cdf856c81656f11e006

test:
  secret_key_base: c11efc151446f77c6485930a754589c7ae8040a978e5468e4b00d9e45d77b758cb431598b10423e56d58e40b627d2390ea6bd65034ffb9ff2a21e652624254d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
